// Generated by scripts/build-package.mjs; do not edit.
/// <reference types="npm:@types/react@^19.0.0" />
export type ReactElement = React.ReactElement;
export type ReactNode = React.ReactNode;
export type CSSProperties = React.CSSProperties;
export type RefObject<T> = React.RefObject<T>;
export type HTMLAttributes<T> = React.HTMLAttributes<T>;
export type Ref<T> = React.Ref<T>;
