/**
 * JSR's npm bridge currently leaves TSX modules as source with npm: imports.
 * Lower JSX to runtime calls while retaining TypeScript annotations and JSDoc.
 * Commit this deterministic tree so the requested `npx jsr publish` workflow
 * works without a build step. Edit src/, then run `npm run package:build`.
 */
import { transformAsync, types as t } from '@babel/core';
import transformJSX from '@babel/plugin-transform-react-jsx';
import { readFile, readdir, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const source = new URL('src/', root);
const target = new URL('publish/', root);
const check = process.argv.includes('--check');
const normalize = (text) => text.replaceAll('\r\n', '\n');
const files = await readdir(source, { recursive: true });
const expected = new Set();
// JSR rewrites React type imports to @types/react in emitted declarations,
// which TypeScript rejects (TS6137). A declaration-only namespace bridge uses
// a valid triple-slash reference instead; it adds no runtime code or new types.
const reactTypeNames = new Set(['ReactElement', 'ReactNode', 'CSSProperties', 'RefObject', 'HTMLAttributes', 'Ref']);
async function save(outputFile, output) {
  expected.add(outputFile);
  const destination = new URL(outputFile, target);
  if (check) {
    const existing = await readFile(destination, 'utf8').catch(() => '');
    if (normalize(existing) !== output) throw new Error(`Stale publish/${outputFile}. Run npm run package:build.`);
  } else {
    await mkdir(new URL('./', destination), { recursive: true });
    await writeFile(destination, output);
  }
}
await save('react-types.d.ts', `// Generated by scripts/build-package.mjs; do not edit.
/// <reference types="npm:@types/react@^19.0.0" />
export type ReactElement = React.ReactElement;
export type ReactNode = React.ReactNode;
export type CSSProperties = React.CSSProperties;
export type RefObject<T> = React.RefObject<T>;
export type HTMLAttributes<T> = React.HTMLAttributes<T>;
export type Ref<T> = React.Ref<T>;
`);
let count = 0;
for (const file of files.filter(f => /\.tsx?$/.test(f)).sort()) {
  const input = normalize(await readFile(new URL(file.replaceAll('\\', '/'), source), 'utf8'));
  const filename = file.replaceAll('\\', '/');
  const outputFile = filename.replace(/\.tsx$/, '.ts');
  expected.add(outputFile);
  const result = await transformAsync(input, {
    filename, babelrc: false, configFile: false, comments: true,
    parserOpts: { sourceType: 'module', plugins: ['typescript', 'jsx'] },
    plugins: [
      [transformJSX, { runtime: 'automatic', importSource: 'react' }],
      () => ({ visitor: { ImportDeclaration(path) {
        if (path.node.source.value !== 'react') return;
        const typeOnly = path.node.specifiers.filter(s => path.node.importKind === 'type' || s.importKind === 'type');
        if (!typeOnly.length) return;
        for (const specifier of typeOnly) {
          if (!reactTypeNames.has(specifier.imported?.name)) throw new Error(`Add ${specifier.imported?.name} to the React declaration bridge.`);
        }
        const bridge = '../'.repeat(filename.split('/').length - 1) + 'react-types.d.ts';
        const declaration = t.importDeclaration(typeOnly.map(s => t.importSpecifier(s.local, s.imported)), t.stringLiteral(bridge.startsWith('.') ? bridge : './' + bridge));
        declaration.importKind = 'type';
        path.node.specifiers = path.node.specifiers.filter(s => !typeOnly.includes(s));
        path.insertAfter(declaration);
        if (!path.node.specifiers.length) path.remove();
      }, StringLiteral(path) {
        if (path.node.value.startsWith('.') && path.node.value.endsWith('.tsx')) {
          path.node.value = path.node.value.replace(/\.tsx$/, '.ts');
        }
      } } }),
    ],
  });
  const output = `// Generated from src/${filename}. Run npm run package:build; do not edit.\n${result.code}\n`;
  await save(outputFile, output);
  count++;
}
const extras = (await readdir(target, { recursive: true })).filter(f => /\.tsx?$/.test(f) && !expected.has(f.replaceAll('\\', '/')));
if (extras.length) throw new Error(`Remove obsolete generated files: ${extras.join(', ')}`);
console.log(`${check ? 'Verified' : 'Generated'} ${count} JSX-free TypeScript modules in ${fileURLToPath(target)}.`);
